### ISSUE TITLE
no child callbacks listed, plus a runtime error

### ISSUE THREAD

**Issue by ntuckerxx** [ConradIrwin/async-profile#1]
I might be misunderstanding the usage of this module, but I tried a simple test which walks a directory and attempts to profile it, and I can't get it to do anything beyond printing the summary and then crashing.  Here's my test code:

``` javascript
    var AsyncProfile = require('async-profile');
    var wrench = require('wrench');

    process.nextTick(function(){

        var profile = new AsyncProfile();

        process.nextTick(function(){
            // note: "music" is a deep directory tree with lots of files
            wrench.readdirRecursive("music", function(error, curFiles) {
                if(!error && curFiles) {
                    curFiles.forEach(function(f) {
                        console.log("file: " + f);
                    });
                }
            });
        });
    });
```

And here's my output:

```
[list of files printed by script removed]
total: 2018.866ms (in 3909.790ms real time, CPU load: 0.5, wait time: 12731813.305ms)

/Users/ntucker/testprof/node_modules/async-profile/lib/index.js:233
      stack = Error.prepareStackTrace(new Error("ohai"), stack);
                    ^
TypeError: Property 'prepareStackTrace' of object function Error() { [native code] } is not a function
    at AsyncProfile.getLineFromStack (/Users/ntucker/testprof/node_modules/async-profile/lib/index.js:233:21)
    at AsyncProfile.print (/Users/ntucker/testprof/node_modules/async-profile/lib/index.js:220:28)
    at Object.AsyncProfile.opts.callback (/Users/ntucker/testprof/node_modules/async-profile/lib/index.js:60:25)
    at AsyncProfile.after (/Users/ntucker/testprof/node_modules/async-profile/lib/index.js:146:19)
    at AsyncProfile.listener.process.createAsyncListener.after (/Users/ntucker/testprof/node_modules/async-profile/lib/index.js:100:26)
    at /Users/ntucker/testprof/node_modules/async-profile/node_modules/async-listener/glue.js:185:42
    at Object.oncomplete (fs.js:107:15)
$ node -v
v0.10.26
$
```

**Comment by halfdan** [comment]
@ntuckerxx Having the exact same issue.

**Comment by ConradIrwin** [comment]
Fixed in `v0.3.1`. Thanks! (I'd not tested it without coffeescript being loaded).

**Comment by ntuckerxx** [comment]
I'm still not sure this is working correctly for me.  The output is more or less useless because it is just pages and pages of this type of thing:

```
68.201: 0.002ms      [no mark] (0.000)
68.215: 0.023ms      [no mark] (0.031)
69.840: 0.400ms        [no mark] (0.306)
75.612: 0.030ms          [no mark] (0.050)
82.621: 4.224ms            [no mark] (4.992)
134.213: 0.002ms              [no mark] (0.000)
134.227: 0.001ms              [no mark] (0.000)
134.241: 0.002ms              [no mark] (0.000)
134.266: 0.004ms              [no mark] (0.000)
134.292: 0.002ms              [no mark] (0.000)
134.305: 0.002ms              [no mark] (0.000)
134.318: 0.001ms              [no mark] (0.000)
144.404: 0.018ms              [no mark] (0.000)
```

Are there supposed to be function names?
